### ISSUE TITLE
start new Telematrix instance

### ISSUE THREAD

**Issue by betz** [SijmenSchoon/telematrix#51]
Hi,

I am trying to setup a new telematrix instance.
I followed the installation instructions, added the path to app_service_config_files in my homeserver.yaml file.
Restarted the homeserver, which works fine.
But do I need to run the 'app_service.py' or something?
when i call 'python app_service.py' i get following error:

`Traceback (most recent call last):
  File "app_service.py", line 1, in <module>
    import telematrix
  File "/etc/telematrix/telematrix/__init__.py", line 108
    async def download_matrix_file(url, filename):
            ^
SyntaxError: invalid syntax`

When i say /alias in the telegram room the bot is in, or to the pot in private, i get no response.

I am a bit lost there. If anyone can help me out, that would be great.
Cheers,
Tom

**Comment by betz** [comment]
ok, after a retry, got it working now.
Closing issue
